# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PeriodicTable' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PeriodicTable
  # pod 'RxRealm', '0.6.0'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  # pod 'Kingfisher', '3.9.1'

end
